export const LOGIN = 'LOGIN'

export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'

export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_OCCUPATION = 'UPDATE_OCCUPATION'
export const UPDATE__USER_LOCATION = 'UPDATE__USER_LOCATION'
export const UPDATE_ABOUT_USER = 'UPDATE_ABOUT_USER'

export const UPDATE_PHOTO = 'UPDATE_PHOTO'







